[package]
name = "codi_bootload"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
panic-abort = "0.3.2"

[dependencies.stm32l4]
version = "0.14.0"
features = ["stm32l4x6", "rt"]

[dependencies.stm32-hal2]
version = "1.3.1"
features = ["l4x6", "embedded-hal"]

[profile.dev]
debug = true
lto = true
codegen-units = 1
incremental = false
opt-level = "s"

[profile.release]
debug = true
lto = true
codegen-units = 1
incremental = false
opt-level = "s"
